services:
  web:
    build: .
    container_name: ritmixlove-cms
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./uploads:/usr/share/nginx/html/uploads
      - ./content:/usr/share/nginx/html/content
    environment:
      - TZ=Asia/Almaty
